### ISSUE TITLE
Finalizing login failed! Reason: undefined

### ISSUE THREAD

**Issue by nueverest** [amark/gun#474]
I'm getting this error: 
**Finalizing login failed! Reason: undefined**

I should be clear that the user is definitely in the db otherwise the error would be: 
**Login Auth attempt failed! Reason: No user!**

Also, this code was working just fine last week and no changes appear in version control.

This is my code:

**HTML**
```
<div class="row">
     <div class="small-12 columns bold margin-top-30">Login</div>
    <div class="small-12 columns margin-top-20">Username:<br /><input id="loginUsername" /></div>
    <div class="small-12 columns margin-top-10">Password:<br /><input id="loginPassword" type="password" /></div>
    <div class="small-12 columns margin-top-10">
        <div id="loginUserBtn" class="inline-block cursor-pointer bgc-h0c71c3 bgc-blue-hover white bold padding-10 border-radius-5">Login</div> 
    </div>
    <div id="loginResult" class="small-12 columns bold margin-top-10"></div>
</div>
```

**JAVASCRIPT**
```
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/gun/gun.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/gun/lib/cryptomodules.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/gun/sea.js"></script>

<script type="text/javascript">
$(document).ready(function () {
     var gun = Gun();
     var user = gun.user();

     $('#loginUserBtn').on('click', function (event) {
         event.preventDefault();

         console.log($('#loginUsername').val(), $('#loginPassword').val());

         // Browser Native Web Crypto API is used to PBKDF2 extend your password.
         user.auth($('#loginUsername').val(), $('#loginPassword').val(), function (ack) {
             console.log(ack);
             console.log(ack.pub, ack.err);

             if (ack.pub !== '' && ack.err === '') {
                 console.log(ack);
                 $('#loginResult').html('<span class="green">User: "' + $('#loginUsername').val() + '" login success.</span>');
                 setProfileData();
             }
             else if (ack.err !== '') {
                 if (ack.err.indexOf('secret') > 0) {
                     var error = ' <span class="red">Password incorrect.</span>';
                     $('#loginResult').html(error);
                 }
                 else {
                     $('#loginResult').html('<span class="red">' + ack.err + '</span>');
                 }
             }
             else {
                 $('#loginResult').html('Failed to login.');
             }
         });
     });
 });
</script>
```

**Comment by amark** [comment]
@nueverest sorry you are experiencing this. I wonder if it has to do with a race condition that I just recently fixed in SEA, that I haven't published yet. Hopefully I'll have it published soon.

If that doesn't fix it, I'll have to debug using your example more. Thanks for showing a relatively simple example for me to test against!

**Comment by amark** [comment]
@nueverest I haven't changed any code, and now randomly I'm getting a bunch of these errors! And I can't figure out why... Will let you know if I make any progress.

**Comment by amark** [comment]
@nueverest I discovered that **I** had written a bug in my user-facing code that caused this error, and it wasn't in SEA. To improve debugging, I added `try{}catch(e){}` which should source out the actual problem now, I just published a new version of SEA, please try again and let me know!

**Comment by nueverest** [comment]
I just had an opportunity to try again, but I'm still getting the same error.

I did not change these.

```
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/gun/gun.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/gun/lib/cryptomodules.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/gun/sea.js"></script>
```

**Comment by amark** [comment]
@nueverest I fixed this by adding a `user.leave()` call on every login/create error, which then let subsequent logins behave correctly. Thank you for reporting this! It is fixed now. If you have any further problems (SEA is in alpha, so I'm sure there will be), let us know!

**Comment by nueverest** [comment]
I came back to this issue again.  I have not changed the code sample above, and now the error changed.

Steps to reproduce:
Open the page
Add create a user (this works)
Login the newly created user

This fails with error:

> Auth attempt failed! Reason: Cannot read property 'indexOf' of undefined

When I click the login button a second time nothing happens.
When I click the login button a third time more I see:

> User is already being created or authenticated!

Not sure what I'm doing wrong.

**Comment by amark** [comment]
@nueverest thanks for the report - quick question if you happen to have it: What is the line number on the error for the `indexOf`?
