### ISSUE TITLE
SEA Login stalls if not fast connection to relay peer

### ISSUE THREAD

**Issue by icarito** [amark/gun#951]
If I move to a peer at localhost, I can login, or offline. But with a peer that has a bad connection (like my Internet connection) it fails most times. I can reproduce for the relay host at localhost if I setup network throthling to "Slow 3G" on Chromium. Then if I try to login most of the time it will stall and not do anything and then if I try again it will say that it's already trying to login.

**Comment by icarito** [comment]
Oh, as a reference, my auth code is here:
https://gitlab.com/fuentelibre/intergambio/-/blob/master/static/eco_db_auth.vue

It's a Vue Component written in Python (that gets transpiled to Javascript).

The app is visible at https://mercalocal.fuentelibre.org/ (sorry it's Spanish for now).

**Comment by icarito** [comment]
Hi,
It looks like this issue was caused by drifting clocks. I added `nts.js` into my imports and now it _seems_ to be allowing login reliably again. Closing!

Thank you and @Dletta who suggested this fix! 
Note "skyfall" from Discord was also affected.

**Comment by icarito** [comment]
A note that `nts` seems to have _helped_ but not solved, because for instance my phone can't login, either from Chromium or Firefox (Fenned F-Droid), in PWA mode.
The app lives at https://mercalocal.fuentelibre.org/ it's meant as a PWA, it very often fails for me to login the first time from a new client, seems to have to do with link speed / reliability.
After first login it seems that it can login locally, this is what `nts` seems to have fixed. But the first login seems to be the problematic one now.

**Comment by sirpy** [comment]
@icarito 
are you having a problem to login from a "CLEAN" client with an "EXISTING" user?
for example you opened an account on desktop and then you try to login with same user on mobile?
In such case i've noticed there could be issues with gun.
I usually make sure i've read the username data from gun before trying to login
something like gun.get('~@username',{wait:2000}) this will wait 2 seconds for server response.
to see my exact hack checkout the .onThen method in gundb-extend.js file at github.com/GoodDollar/GoodDAPP

**Comment by icarito** [comment]
Thank you I will test it and get back to you!

**Comment by icarito** [comment]
Thanks for your pointer! Although I tried to understand your code at https://github.com/GoodDollar/GoodDAPP/blob/master/src/lib/gundb/gundb-extend.js#L11 - I didn't. But from your description I implemented awaiting for $gun.get username before attempting to authenticate, and I was unable to reproduce the problem, so it seems your workaround fixes for me!
Great!
Still going to leave this open as it's definitively a bug IMHO. Thanks @sirpy !

**Comment by sirpy** [comment]
you should look at onThen method
it uses both .once and .on to first read user data from server. if you will
use only .once in your code the issue might still happen. because .once
usually waits for a short time for server response

**Comment by icarito** [comment]
I see, it's still a bit unclear for me how onThen does it. From your description I didn't use `.on` or `.once` but only used async `.get` (sorry for the Python it gets transpiled to JS):

```python
async def authenticate(self):
        user = await self['$gun'].get('~@'+self.username, {'wait':2000})
        if user:
            self.user.auth(self.username, self.password, self.result)
            self.user.recall({'sessionStorage':True}, self.result)
        else:
            self.result({'err':'Unable to login')
```
This seems to be working as you described, I can login apparently reliably, and I try with an unknown user while offline, I get "Unable to login".

**Comment by sirpy** [comment]
there are some situations that get (async=once promisified) will return
undefined even with wait 2000. it could have been fixed in newer versions.
but it is not common in any case.
.on always returns something if it exists, but if it doesn't exist then it
will never return. that's why I do a race between .on and .once verifying
they are not undefined and only if both timeout then I consider the user as
non existent ie new
